### ISSUE TITLE
Error on create instance of Messegner

### ISSUE THREAD

**Issue by diegoaraujolima** [MohammadFneish7/WhatsappAgent#12]
System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\TesteWhatsApp\WinFormsApp1\WinFormsApp1\bin\Debug\net6.0-windows\chrome\chrome.zip'.'

**Comment by MAKFneish** [comment]
Hello @diegoaraujolima,
This could be a bug, until we confirm it please revert back to an older version
