### ISSUE TITLE
how can i add newline inside a message.

### ISSUE THREAD

**Issue by alhuntre** [MohammadFneish7/WhatsappAgent#14]
Hello, 

How to add NewLine inside a message?
i tried multiple soultion but i didnt find a way to add new line.
Example:

**Hi there,
Message....
Best Regards.**

thank you

**Comment by MAKFneish** [comment]
Hello @mawadidres,
if you are using the demo application, then this is not supported, it is just a demo. However if you are using the library code you can do this "Hi there,\nMessage....\nBest Regards."
