### ISSUE TITLE
Login is not detected.

### ISSUE THREAD

**Issue by albertocolombo73** [MohammadFneish7/WhatsappAgent#6]
Hi to all,

After invoking Messenger.Login(100) with time out, login is not detected. How to solve the problem? Thanks to anyone who wants to help me.

Alberto

**Comment by ackid50** [comment]
new version solved the problem

**Comment by albertocolombo73** [comment]
Thank you. Login now is detected! Thanks a lot!
There seems to be another problem related to the language, for this reason I will open a new issue.
Alberto

**Comment by MAKFneish** [comment]
Whatsapp has changed thier code, we must keep tracking their changes, the new version fixes this issue.
