### ISSUE TITLE
Unable to send text and media, WaitForCSSElemnt timeout

### ISSUE THREAD

**Issue by albertocolombo73** [MohammadFneish7/WhatsappAgent#7]
Hi to all,

It seems that the WaitForCSSElemnt method for the selector "[title='Type a message']" times out because it can't find the selector. The code is as follows:
var textbox = WaitForCSSElemnt("[title='Type a message']", load_timeout);

After debugging I noticed that, in my case, it expects a label in Italian language like the following:
var textbox = WaitForCSSElemnt("[title='Scrivi un messaggio']", load_timeout);

How to solve this problem to accept all language label? Thank you in advance.

Alberto

**Comment by MAKFneish** [comment]
Whatsapp has changed thier code, we must keep tracking their changes, the new version fixes this issue.
