### ISSUE TITLE
sendmedia issue

### ISSUE THREAD

**Issue by ackid50** [MohammadFneish7/WhatsappAgent#9]
When I try to send media with a message continuously,  often it send message only. The attached image is missing. Please look at this.

**Comment by MAKFneish** [comment]
Try to increase the timeout

**Comment by ackid50** [comment]
Thanks, let me check and report soon

**Comment by ackid50** [comment]
When I increase the timeout,  the sendmedia is working with alternative messages - see the screen shot 

https://drive.google.com/file/d/1fMYKB30pdc2QC6H_i0Xb36LMyQosQEzF/view?usp=sharing

and it is perfectly send every alternative messages.

**Comment by ackid50** [comment]
Actually there is no time out error coming, it assumes that the media was sent. And report as sent.
